# Assignment Chapter 2 - MACHINE LEARNING [Case #1]
Startup Campus, Indonesia - `Artificial Intelligence (AI)` (Batch 7)
* Dataset: SC_HW1_bank_data
* Libraries: Pandas, Numpy, Scikit-learn
* Objective: Classification with Supervised Machine Learning Models

`PERSYARATAN` Semua modul (termasuk versi yang sesuai) sudah di-install dengan benar.
<br>`CARA PENGERJAAN` Lengkapi baris kode yang ditandai dengan **#TODO**.
<br>`TARGET PORTFOLIO` Peserta mampu membandingkan akurasi klasifikasi dari berbagai model *supervised learning*.

### Import Library

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Read Dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.head()

RowNumber  CustomerId Geography  Gender  Age  Tenure    Balance  \
0          1    15634602    France  Female   42       2       0.00   
1          2    15647311     Spain  Female   41       1   83807.86   
2          3    15619304    France  Female   42       8  159660.80   
3          4    15701354    France  Female   39       1       0.00   
4          5    15737888     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [ ]:
# TODO: Hilangkan kolom yang tidak relevan untuk pemodelan
df = df[df.columns[2:]].copy()
df.head()

Geography  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0    France  Female   42       2       0.00              1          1   
1     Spain  Female   41       1   83807.86              1          0   
2    France  Female   42       8  159660.80              3          1   
3    France  Female   39       1       0.00              2          0   
4     Spain  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

### Preprocessing

In [ ]:
# TODO: Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
df = pd.get_dummies(df, columns=['Geography', 'Gender']).astype(int)
df.head()

Age  Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42       2        0              1          1               1   
1   41       1    83807              1          0               1   
2   42       8   159660              3          1               0   
3   39       1        0              2          0               0   
4   43       2   125510              1          1               1   

   EstimatedSalary  Exited  Geography_France  Geography_Germany  \
0           101348       1                 1                  0   
1           112542       0                 0                  0   
2           113931       1                 1                  0   
3            93826       0                 1                  0   
4            79084       0                 0                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0

In [ ]:
# TODO: Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
X = df.drop(columns=['Exited'])
y = df['Exited']

In [ ]:
scaler = MinMaxScaler() # TODO: Lakukan scaling atau normalisasi
X_transform = scaler.fit_transform(X)
#print(X_transform)

In [ ]:
# Bagian ini digunakan jika Anda melakukan scaling atau normalisasi.
# Jika tidak, code ini bisa dilewati dan diganti dengan code yang ada di dalam comment.

X_transform = pd.DataFrame(X_transform, columns = X.columns)
# X_transform = X.copy()

In [ ]:
X_transform.head()

Age  Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0  0.324324     0.2  0.000000       0.000000        1.0             1.0   
1  0.310811     0.1  0.334028       0.000000        0.0             1.0   
2  0.324324     0.8  0.636354       0.666667        1.0             0.0   
3  0.283784     0.1  0.000000       0.333333        0.0             0.0   
4  0.337838     0.2  0.500243       0.000000        1.0             1.0   

   EstimatedSalary  Geography_France  Geography_Germany  Geography_Spain  \
0         0.506733               1.0                0.0              0.0   
1         0.562708               0.0                0.0              1.0   
2         0.569654               1.0                0.0              0.0   
3         0.469120               1.0                0.0              0.0   
4         0.395403               0.0                0.0              1.0   

   Gender_Female  Gender_Male  
0            1.0          0.0  
1            1.0          0.0  
2            1.0          0.0  
3            1.0          0.0  
4            1.0          0.0

### Train-Test Split

In [ ]:
X_train ,X_test, y_train, y_test = tts(X_transform, y, test_size = 0.25, random_state = 123)

### Model #1

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #1 yang Anda gunakan.

[ ANSWER HERE ]
<br>Random Forest merupakan gabungan dari beberapa Decision Tree. Cara kerjanya adalah melakukan "voting" dari beberapa Decision Tree tersebut. Penentuan hasil klasifikasinya berdasarkan "vote" terbanyak.

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator= model1,
    param_grid= params,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid.fit(X_train,y_train)
grid.best_params_

{'bootstrap': True,
 'max_depth': 10,
 'min_samples_leaf': 4,
 'min_samples_split': 2,
 'n_estimators': 300}

In [ ]:
y_pred = grid.best_estimator_.predict(X_test) # TODO: Lakukan evaluasi untuk model #1

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1983
           1       0.79      0.44      0.56       517

    accuracy                           0.86      2500
   macro avg       0.83      0.70      0.74      2500
weighted avg       0.85      0.86      0.84      2500


[[1923   60]
 [ 292  225]]

0.8592


### Model #2

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #2 yang Anda gunakan.

[ ANSWER HERE ]
<br>K-Nearest Neighbour (KNN) merupakan metode klasifikasi dengan cara mencari jarak terdekat di antara 2 kelas. Di model2 disimulasikan pencarian jarak terdekat menggunakan pendekatan Euclidean dan Manhattan. Adapun setelah dilakukan tuning hasil yang lebih baik didapat ketika menggunakan pendekatan Manhattan dalam pencarian jarak terdekat dengan jumlah *neighbor* sebanyak 9.

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier()
params = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator= model2,
    param_grid= params,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid.fit(X_train,y_train)
grid.best_params_

{'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'distance'}

In [ ]:
y_pred = grid.best_estimator_.predict(X_test) # TODO: Lakukan evaluasi untuk model #2

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90      1983
           1       0.67      0.33      0.45       517

    accuracy                           0.83      2500
   macro avg       0.76      0.65      0.67      2500
weighted avg       0.81      0.83      0.80      2500


[[1897   86]
 [ 344  173]]

0.828


### Model #3

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #3 yang Anda gunakan.

[ ANSWER HERE ]
<br>Support Vector Machine (SVM) merupakan metode klasifikasi yang digunakan untuk menemukan *hyperplane* terbaik dengan cara memisahkan kelas-kelas data dalam ruang multidimensi. Pada simulasi di model3 digunakan kernel RBF, Polynomial, dan Linear. Adapun hasil yang didapat menggunakan tuning adalah penggunakan Kernel Polynomial memiliki hasil yang terbaik.

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn import svm
model3 = svm.SVC()
params = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'poly', 'linear']
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator= model3,
    param_grid= params,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
)

grid.fit(X_train,y_train)
grid.best_params_

{'C': 100, 'gamma': 1, 'kernel': 'poly'}

In [ ]:
y_pred = grid.best_estimator_.predict(X_test) # TODO: Lakukan evaluasi untuk model #3

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1983
           1       0.79      0.48      0.59       517

    accuracy                           0.87      2500
   macro avg       0.83      0.72      0.76      2500
weighted avg       0.86      0.87      0.85      2500


[[1919   64]
 [ 271  246]]

0.866


### Conclusion

In [ ]:
# [ PERTANYAAN ]
# TODO: Tarik kesimpulan model mana yang terbaik beserta alasannya

[ ANSWER HERE ]
<br>Berikut merupakan summary dari nilai **akurasi** masing-masing model:
- Model 1 - Random Forest = 85,92%
- Model 2 - KNN = 82,8%
- Model 3 - SVM = 86,6%

Berdasarkan nilai akurasi tersebut, model terbaik untuk klasifikasi data ini adalah **SVM**.

### Scoring
Total `#TODO` = 13
<br>Checklist:

- [ ] Hilangkan kolom yang tidak relevan untuk pemodelan
- [ ] Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
- [ ] Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
- [ ] Lakukan scaling atau normalisasi
- [ ] Jelaskan secara singkat model #1 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #1)
- [ ] Lakukan evaluasi untuk model #1
- [ ] Jelaskan secara singkat model #2 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #2)
- [ ] Lakukan evaluasi untuk model #2
- [ ] Jelaskan secara singkat model #3 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #3)
- [ ] Lakukan evaluasi untuk model #3

### Additional readings
- N/A

### Copyright © 2024 Startup Campus, Indonesia
* You may **NOT** use this file except there is written permission from PT. Kampus Merdeka Belajar (Startup Campus).
* Please address your questions to mentors.